### ISSUE TITLE
Devs can build, test and use Open Enclave on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by herveyw** [Microsoft/openenclave#232]
Converting this into a story for prioritization in Public Preview timeframe. The initial issue should have workarounds available already, and we need to validate that there are no other issues that prevent either AESM or NGSA builds on Ubuntu 18.04 LTS.

* This is a prerequisite for producing an Ubuntu 18.04 LTS dev image for release on ARM as part of public preview.
* This has a dependency on Intel signing off on their NGSA and FLC driver packages being supported on 18.04 LTS as well.

Hervey's original issue:
> All pre-reqs installed and working, the OpenEnclave build fails with:

> /home/herveyw/git/openenclave/host/crypto/cert.c: In function ‘OE_CertVerify’:
> /home/herveyw/git/openenclave/host/crypto/cert.c:406:61: error: dereferencing pointer to incomplete type ‘X509_STORE_CTX {aka struct x509_store_ctx_st}’
>             _SetErr(error, X509_verify_cert_error_string(ctx->error));
                                                             ^~
> host/CMakeFiles/oehost.dir/build.make:662: recipe for target 'host/CMakeFiles/oehost.dir/crypto/cert.c.o' failed
> make[2]: *** [host/CMakeFiles/oehost.dir/crypto/cert.c.o] Error 1
> CMakeFiles/Makefile2:981: recipe for target 'host/CMakeFiles/oehost.dir/all' failed

**Comment by CodeMonkeyLeet** [comment]
Additional observations from @yakman2020 in #828
> The structure x509_st is no longer visible in the openssh header files. This is by design. It causes the file > (at least) host/crypto/cert.c not to compile do to direct accessing of the structure members.
> openssl/openssl#594 says that the structure needs to be accessed using accessor functions.

**Comment by johnkord** [comment]
This is resolved in master, and we are running Ubuntu 18.04 builds in CI now.
