### PR TITLE
Add Ubuntu 18.04 support to libcxx_tests.Jenkinsfile

### PR DESCRIPTION
**Pull request by oprinmarius**
- Changed libcxx_tests.Jenkinsfile to scripted
- Added  Ubuntu 18.04 tests

fixes https://github.com/Microsoft/openenclave/issues/1278

### CODE REVIEW

**Comment by ionutbalutoiu** [comment]
bors try

**Comment by johnkord** [comment]
As we spoke about, we will wait to merge this until we get gcc builds working for 18.04.

**Comment by ionutbalutoiu** [comment]
@johnkord @anitagov @andschwa 

@aserdean found the cause of the libcxx failures on Ubuntu 18.04.

Our CI is failing to compile libcxx on Ubuntu 18.04 with:
```
cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_LIBSGX=1 -DENABLE_FULL_LIBCXX_TESTS=1
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- The ASM compiler identification is GNU
```
with the output:
https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-libcxx_tests-moprin-temp/detail/OpenEnclave-libcxx_tests-moprin-temp/1/pipeline/#step-143-log-1075

This is caused by https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83921 as pointed out by the file:
https://github.com/Microsoft/openenclave/blob/master/3rdparty/libcxx/libcxx/test/std/utilities/function.objects/comparisons/constexpr_init.pass.cpp#L19

I’m guessing that we could fan out the test, ifdef it out, or just update the compiler version.

The GNU issue suggests that GCC 8.1.0 could have this solved. We'll have to install it from tarball (the way we do with `cmake`) since the APT stable package is at `7.3.0`.

What do you think is the best approach to go here ? I'd go with getting a new GCC version.

**Comment by ionutbalutoiu** [comment]
> @johnkord @anitagov @andschwa
> 
> @aserdean found the cause of the libcxx failures on Ubuntu 18.04.
> 
> Our CI is failing to compile libcxx on Ubuntu 18.04 with:
> 
> ```
> cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_LIBSGX=1 -DENABLE_FULL_LIBCXX_TESTS=1
> -- The C compiler identification is GNU 7.3.0
> -- The CXX compiler identification is GNU 7.3.0
> -- The ASM compiler identification is GNU
> ```
> with the output:
> https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-libcxx_tests/detail/OpenEnclave-libcxx_tests/198/pipeline/24
> 
> This is caused by https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83921 as pointed out by the file:
> https://github.com/Microsoft/openenclave/blob/master/3rdparty/libcxx/libcxx/test/std/utilities/function.objects/comparisons/constexpr_init.pass.cpp#L19
> 
> I’m guessing that we could fan out the test, ifdef it out, or just update the compiler version.
> 
> The GNU issue suggests that GCC 8.1.0 could have this solved. We'll have to install it from tarball (the way we do with `cmake`) since the APT stable package is at `7.3.0`.
> 
> What do you think is the best approach to go here ? I'd go with getting a new GCC version.



> @johnkord @anitagov @andschwa
> 
> @aserdean found the cause of the libcxx failures on Ubuntu 18.04.
> 
> Our CI is failing to compile libcxx on Ubuntu 18.04 with:
> 
> ```
> cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_LIBSGX=1 -DENABLE_FULL_LIBCXX_TESTS=1
> -- The C compiler identification is GNU 7.3.0
> -- The CXX compiler identification is GNU 7.3.0
> -- The ASM compiler identification is GNU
> ```
> with the output:
> https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-libcxx_tests/detail/OpenEnclave-libcxx_tests/198/pipeline/24
> 
> This is caused by https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83921 as pointed out by the file:
> https://github.com/Microsoft/openenclave/blob/master/3rdparty/libcxx/libcxx/test/std/utilities/function.objects/comparisons/constexpr_init.pass.cpp#L19
> 
> I’m guessing that we could fan out the test, ifdef it out, or just update the compiler version.
> 
> The GNU issue suggests that GCC 8.1.0 could have this solved. We'll have to install it from tarball (the way we do with `cmake`) since the APT stable package is at `7.3.0`.
> 
> What do you think is the best approach to go here ? I'd go with getting a new GCC version.

@johnkord @anitagov @johnkord What's your take here ?

**Comment by johnkord** [comment]
@ionutbalutoiu I just installed gcc-8/g++-8 on my Ubuntu 16.04 system to see if it fixes the problem, but then I hit a different error just trying to build the :

```
[1823/2064] Building CXX object tests/cppException/enc/CMakeFiles/cppException_enc.dir/cppException.cpp.o
FAILED: /usr/bin/g++-8  -DOE_API_VERSION=2 -DOE_BUILD_ENCLAVE -DOE_USE_LIBSGX -Itests/cppException/enc -I../tests/cppException/enc -I../include -I3rdparty/mbedtls/mbedtls-wrap-prefix/src/mbedtls-wrap/include -Ioutput/include/openenclave/libcxx -Ioutput/include/openenclave/libc -g   -Wall -Werror -Wpointer-arith -Wconversion -Wextra -Wno-missing-field-initializers -fno-strict-aliasing -mxsave -fno-builtin-malloc -fno-builtin-calloc -fno-builtin -m64 -fPIC -nostdinc -fno-stack-protector -fvisibility=hidden -nostdinc++ -Wno-implicit-fallthrough -std=c++14 -MD -MT tests/cppException/enc/CMakeFiles/cppException_enc.dir/cppException.cpp.o -MF tests/cppException/enc/CMakeFiles/cppException_enc.dir/cppException.cpp.o.d -o tests/cppException/enc/CMakeFiles/cppException_enc.dir/cppException.cpp.o -c ../tests/cppException/enc/cppException.cpp
../tests/cppException/enc/cppException.cpp: In function ‘bool BasicVerification()’:
../tests/cppException/enc/cppException.cpp:250:23: error: catching polymorphic type ‘class BarClass02’ by value [-Werror=catch-value=]
     catch (BarClass02 ex_obj)
                       ^~~~~~
../tests/cppException/enc/cppException.cpp:325:23: error: catching polymorphic type ‘class BarClass02’ by value [-Werror=catch-value=]
     catch (BarClass02 ex_obj)
                       ^~~~~~
../tests/cppException/enc/cppException.cpp: In function ‘void bar02()’:
../tests/cppException/enc/cppException.cpp:412:12: error: catching polymorphic type ‘class BarClass03’ by value [-Werror=catch-value=]
     catch (BarClass03)
            ^~~~~~~~~~
../tests/cppException/enc/cppException.cpp: In function ‘bool NestedException()’:
../tests/cppException/enc/cppException.cpp:495:23: error: catching polymorphic type ‘class BarClass02’ by value [-Werror=catch-value=]
     catch (BarClass02 ex_obj)
                       ^~~~~~
cc1plus: all warnings being treated as errors
[1823/2064] Building CXX object tests/oeedger8r/enc/CMakeFiles/edl_enc.dir/testarray.cpp.o
ninja: build stopped: subcommand failed.
```

Looks like the gcc-8 compiler doesn't like us catching exceptions by value. We test catching by reference too it appears, so I'm not sure what the right thing to do is here: either disable the tests of catching by value or disable the warning.  Probably disable the warning I imagine! 

Update: I just disabled that warning as an error and hit the same warning again for another test, which I then also disabled as error, and then was able to fully compile and run the tests! The tests are still running so I'm not sure if anything is broken yet. :)

**Comment by anitagov** [comment]
I think upgrading GCC version calls for a separate issue. We may need to modify tests to conform as @johnkord already observed.

@ionutbalutoiu - You can always bucket all the tests that require a newer version of GCC and if this list is really large, then we may need to move. But otherwise, we disable tests based on the version of GCC and Ubuntu 18.04 in this case in the CMakeLists.txt. Don't put them in tests.unsupported as they will not run on any configuration.

Can we get a list of tests that require GCC 8?

**Comment by ionutbalutoiu** [comment]
Hello! The libcxx tests work with Ubuntu 18.04 as well, now. We just rebased this PR on top of https://github.com/Microsoft/openenclave/pull/1542, and we're good to merge.

bors r+
